### PR TITLE
fix: add missing translations

### PR DESCRIPTION
**Pull request by heavybeard**
Add a string to translations

Open to changes

### CODE REVIEW

**Comment by oliverlaz** [comment]
hi @heavybeard, many thanks for your contribution, and for adding the missing translation keys.

We would gladly accept your contribution if you remove the `it.json` file from this PR.

For localizing your app, we recommend managing the translations by yourself, as that is going to be faster for you to make adjustments in the long run.
You can follow this guide: https://getstream.io/video/docs/react/advanced/i18n/

Please let us know in case you need any support.

**Comment by heavybeard** [comment]
@oliverlaz PR updated with removing of italian translations

**Review by oliverlaz — APPROVED** [review]

**Comment by oliverlaz** [comment]
hey @heavybeard, one more thing before we merge this PR. 

Can you please fill in and sign this CLA?
- https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform

**Comment by heavybeard** [comment]
@oliverlaz done

**Comment by oliverlaz** [comment]
Released in [v0.3.45](https://github.com/GetStream/stream-video-js/releases/tag/%40stream-io%2Fvideo-react-sdk-0.3.45)

Thank you!

**Pull request merged**
