### PR TITLE
docs(react-sdk): rename 13-custom-call-layout.mdx to 04-video-layout.mdx

### PR DESCRIPTION
**Pull request by MartinCupela**

### CODE REVIEW

**Comment by arnautov-anton** [comment]
So - my understanding is that we're dropping "call layouts" for "video layouts"? If that's the case then we should probably adjust all of the occurences across the whole documentation and probably rename folders in the SDK as well.

**Comment by MartinCupela** [comment]
> So - my understanding is that we're dropping "call layouts" for "video layouts"? If that's the case then we should probably adjust all of the occurences across the whole documentation and probably rename folders in the SDK as well.

I don't think that documentation title has to force the names used in code.

**Comment by arnautov-anton** [comment]
> > So - my understanding is that we're dropping "call layouts" for "video layouts"? If that's the case then we should probably adjust all of the occurences across the whole documentation and probably rename folders in the SDK as well.
> 
> I don't think that documentation title has to force the names used in code.

I believe it could cause a confusion or two when you read a guide on a "video layout" but everywhere else in the docs we refer to these as "call layouts".

**Comment by szuperaz** [comment]
> > > So - my understanding is that we're dropping "call layouts" for "video layouts"? If that's the case then we should probably adjust all of the occurences across the whole documentation and probably rename folders in the SDK as well.
> > 
> > 
> > I don't think that documentation title has to force the names used in code.
> 
> I believe it could cause a confusion or two when you read a guide on a "video layout" but everywhere else in the docs we refer to these as "call layouts".

I would also update the docs, it's confusing to have two different names

**Review by oliverlaz — APPROVED** [review]

**Pull request merged**
